# Dane do połączenia z bazą w Dockerze
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# To sprawi, że Spring sam stworzy tabele w bazie na starcie
spring.jpa.hibernate.ddl-auto=update

# Dzięki temu zobaczysz w konsoli, jak Spring "rozmawia" z bazą przez SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true